#ifndef CLEARVIDEO_SETLPASVLOFFSCREEN_H
#define CLEARVIDEO_SETLPASVLOFFSCREEN_H

#include <asvloffscreen.h>
#include "single_image_enhancement_define.h"

MInt32 SetLPASVLOFFSCREEN(LPASVLOFFSCREEN pSrcDst, MUInt8 *pMemory, MInt32 lWidth, MInt32 lHeight, MInt32 lStride, MInt32 lPAF);
MInt32 AllocLPASVLOFFSCREEN(MHandle hMemMgr, LPASVLOFFSCREEN pSrcDst, MInt32 lWidth, MInt32 lHeight, MInt32 lStride, MInt32 lPAF);
MInt32 AllocLPASVLOFFSCREEN(MHandle hMemMgr, LPASVLOFFSCREEN pSrcDst, LPASVLOFFSCREEN pRef);
MVoid FreeLPASVLOFFSCREEN(MHandle hMemMgr, LPASVLOFFSCREEN pSrcDst);
MVoid RectLPASVLOFFSCREEN(LPASVLOFFSCREEN pSrc, LPASVLOFFSCREEN pDst, Rect* pRoi);
MRESULT CopyY(LPASVLOFFSCREEN pDstImg, LPASVLOFFSCREEN pSrcImg);
MRESULT CopyUV(LPASVLOFFSCREEN pDstImg, LPASVLOFFSCREEN pSrcImg);
MRESULT CopyOffscreen(LPASVLOFFSCREEN pDstImg, LPASVLOFFSCREEN pSrcImg);

#endif //CLEARVIDEO_SETLPASVLOFFSCREEN_H
